# MODELLER script for single template homology modeling
# Generated by AlphaBald Pipeline

from modeller import *
from modeller.automodel import *

# Set up environment
env = Environ()
env.io.atom_files_directory = ['.', '../Templates', '../Modeller_Templates']

# Create alignment object
aln = Alignment(env)

# Build model using automodel class
class MyModel(AutoModel):
    def special_patches(self, aln):
        # Override to add special patches if needed
        pass

a = MyModel(
    env,
    alnfile='Modeller_Templates/alignment.pir',
    knowns='1rc2',
    sequence='TM_Protein',
    assess_methods=(assess.DOPE, assess.GA341)
)

# Set model parameters
a.starting_model = 1
a.ending_model = 5

# Generate models
a.make()

# Print summary of results
print("\n" + "="*60)
print("MODEL ASSESSMENT SUMMARY")
print("="*60)
for model in a.outputs:
    print(f"Model: {model['name']}")
    print(f"  DOPE score: {model['DOPE score']:.2f}")
    print(f"  GA341 score: {model['GA341 score'][0]:.4f}")
    print("-"*40)
