>P1;1nkp
structureX:1nkp:897:A:984:A::::
GHMNVKRRTHNVLERQRRNELKRSFFALRDQIPELENNEKAPKVVILKKATAYILSVQAEEQKLISEEDLLRKRREQLKHKLEQLGGC*

>P1;ChainA
sequence:ChainA::::::::
NVKRRTHNVLERQRRNELKRSFFAFRDQIPELENNEKAPKVVILKKFTATATATTAYILSVQAEEQKLISEEDLLRKRREQLKHKLEQL*
