>P1;1an2
structureX:1an2:22:A:107:A::::
ADKRAHHNALERKRRDHIKDSFHSLRDSVPSLQGEKASRAQILDKATEYIQYMRRKNHTHQQDIDDLKRQNALLEQQVRALEKARS*

>P1;ChainB
sequence:ChainB::::::::
DALAHHNALELDLADHIKDSFHSLSLFLDSVPSLQGEKASRAQILDKFTEYIQYMRRKNHTHQQDIDDLKRQNALLEQQVRAL*
