"""
PyMOL visualization utilities for protein structure analysis.

Provides functions to generate publication-quality figures for:
- Active site visualization
- Secondary structure highlighting
- Model quality assessment
- Domain visualization

Requires: PyMOL (installed in AlphaBald conda environment)

Example Usage
-------------
>>> from src.Analysis.visualization import ActiveSiteVisualizer
>>> viz = ActiveSiteVisualizer("model.pdb")
>>> viz.highlight_active_site([123, 156, 189], output="active_site.png")
"""

from pathlib import Path
from typing import List, Dict, Optional, Tuple
import subprocess


def generate_pymol_script(
    pdb_file: str,
    output_image: str,
    commands: List[str],
    width: int = 1200,
    height: int = 900,
    ray: bool = True
) -> str:
    """
    Generate a PyMOL script with common setup.

    Parameters
    ----------
    pdb_file : str
        Input PDB file
    output_image : str
        Output image path (PNG)
    commands : list
        List of PyMOL commands to execute
    width : int
        Image width in pixels
    height : int
        Image height in pixels
    ray : bool
        Whether to ray-trace the image

    Returns
    -------
    str
        PyMOL script content
    """
    script = f"""# PyMOL script generated by AlphaBald
# Load structure
load {pdb_file}, model

# Basic setup
bg_color white
set ray_opaque_background, on
set antialias, 2
set ray_shadows, 0
set depth_cue, 0

# Apply custom commands
"""
    script += "\n".join(commands)

    script += f"""

# Render and save
viewport {width}, {height}
"""
    if ray:
        script += "ray\n"
    script += f"png {output_image}, dpi=300\n"
    script += "quit\n"

    return script


def run_pymol_script(script_content: str, script_path: str = "temp/pymol_script.pml") -> bool:
    """
    Run a PyMOL script.

    Parameters
    ----------
    script_content : str
        PyMOL script content
    script_path : str
        Path to save the script

    Returns
    -------
    bool
        True if successful
    """
    script_file = Path(script_path)
    script_file.parent.mkdir(exist_ok=True)

    with open(script_file, 'w') as f:
        f.write(script_content)

    try:
        result = subprocess.run(
            ['pymol', '-cq', str(script_file)],
            capture_output=True,
            text=True,
            timeout=120
        )
        if result.returncode == 0:
            print(f"PyMOL script executed successfully")
            return True
        else:
            print(f"PyMOL error: {result.stderr}")
            return False
    except FileNotFoundError:
        print("PyMOL not found. Make sure the AlphaBald conda environment is activated.")
        return False
    except Exception as e:
        print(f"Error running PyMOL: {e}")
        return False


def visualize_active_site(
    pdb_file: str,
    active_site_residues: List[int],
    output_file: str,
    conserved_residues: List[int] = None,
    non_conserved_residues: List[int] = None,
    show_surface: bool = True,
    label_residues: bool = True
) -> bool:
    """
    Generate active site visualization.

    Parameters
    ----------
    pdb_file : str
        Input PDB file
    active_site_residues : list
        List of active site residue numbers
    output_file : str
        Output image file (PNG)
    conserved_residues : list, optional
        Residues that are conserved (shown in green)
    non_conserved_residues : list, optional
        Residues that are not conserved (shown in red)
    show_surface : bool
        Show molecular surface around active site
    label_residues : bool
        Label the residues

    Returns
    -------
    bool
        True if successful
    """
    if conserved_residues is None:
        conserved_residues = active_site_residues
    if non_conserved_residues is None:
        non_conserved_residues = []

    # Build residue selections
    all_residues = "+".join(str(r) for r in active_site_residues)
    conserved_sel = "+".join(str(r) for r in conserved_residues) if conserved_residues else ""
    non_conserved_sel = "+".join(str(r) for r in non_conserved_residues) if non_conserved_residues else ""

    commands = [
        "# Hide everything first",
        "hide everything",
        "",
        "# Show cartoon for context",
        "show cartoon, model",
        "color gray80, model",
        "set cartoon_transparency, 0.7",
        "",
        f"# Select active site residues",
        f"select active_site, resi {all_residues}",
        "",
        "# Show active site as sticks",
        "show sticks, active_site",
        "set stick_radius, 0.15",
        "",
    ]

    # Color conserved and non-conserved residues
    if conserved_sel:
        commands.extend([
            f"# Color conserved residues (green)",
            f"select conserved, resi {conserved_sel}",
            "color green, conserved",
        ])
    if non_conserved_sel:
        commands.extend([
            f"# Color non-conserved residues (red)",
            f"select non_conserved, resi {non_conserved_sel}",
            "color red, non_conserved",
        ])

    if show_surface:
        commands.extend([
            "",
            "# Show transparent surface around active site",
            "create surface_obj, active_site expand 5",
            "show surface, surface_obj",
            "set surface_color, white, surface_obj",
            "set transparency, 0.6, surface_obj",
        ])

    if label_residues:
        commands.extend([
            "",
            "# Label residues",
            "label active_site and name CA, '%s%s' % (resn, resi)",
            "set label_size, 14",
            "set label_color, black",
        ])

    commands.extend([
        "",
        "# Center and orient view",
        "center active_site",
        "zoom active_site, 8",
        "orient active_site",
    ])

    script = generate_pymol_script(pdb_file, output_file, commands)
    return run_pymol_script(script)


def visualize_problematic_regions(
    pdb_file: str,
    problematic_regions: List[Tuple[int, int]],
    output_file: str,
    dssp_data: Dict = None
) -> bool:
    """
    Visualize problematic regions in a model.

    Parameters
    ----------
    pdb_file : str
        Input PDB file
    problematic_regions : list
        List of (start, end) tuples for problematic regions
    output_file : str
        Output image file
    dssp_data : dict, optional
        DSSP secondary structure data for coloring

    Returns
    -------
    bool
        True if successful
    """
    commands = [
        "# Show cartoon representation",
        "hide everything",
        "show cartoon, model",
        "",
        "# Color by secondary structure",
        "color red, ss h",  # Helices
        "color yellow, ss s",  # Sheets
        "color green, ss l+''",  # Loops/coils
        "",
    ]

    # Highlight problematic regions
    for i, (start, end) in enumerate(problematic_regions):
        commands.extend([
            f"# Problematic region {i+1}: {start}-{end}",
            f"select problem_{i+1}, resi {start}-{end}",
            f"color magenta, problem_{i+1}",
            f"show sticks, problem_{i+1}",
        ])

    commands.extend([
        "",
        "# Orient view",
        "orient",
        "zoom",
    ])

    script = generate_pymol_script(pdb_file, output_file, commands)
    return run_pymol_script(script)


def visualize_secondary_structure(
    pdb_file: str,
    output_file: str,
    highlight_regions: Dict[str, List[Tuple[int, int]]] = None
) -> bool:
    """
    Visualize secondary structure with optional highlighting.

    Parameters
    ----------
    pdb_file : str
        Input PDB file
    output_file : str
        Output image file
    highlight_regions : dict, optional
        Dictionary with 'helix', 'sheet', 'loop' keys mapping to
        list of (start, end) tuples to highlight

    Returns
    -------
    bool
        True if successful
    """
    commands = [
        "# Show cartoon representation",
        "hide everything",
        "show cartoon, model",
        "",
        "# Color by secondary structure",
        "set cartoon_fancy_helices, 1",
        "set cartoon_flat_sheets, 1",
        "color red, ss h",  # Alpha helices
        "color yellow, ss s",  # Beta sheets
        "color gray70, ss l+''",  # Loops
        "",
        "# Enhance visualization",
        "set cartoon_highlight_color, gray90",
        "set cartoon_smooth_loops, 1",
    ]

    if highlight_regions:
        for ss_type, regions in highlight_regions.items():
            color = {'helix': 'magenta', 'sheet': 'orange', 'loop': 'cyan'}.get(ss_type, 'white')
            for start, end in regions:
                commands.append(f"color {color}, resi {start}-{end}")

    commands.extend([
        "",
        "# Orient and render",
        "orient",
        "zoom",
    ])

    script = generate_pymol_script(pdb_file, output_file, commands)
    return run_pymol_script(script)


def visualize_cation_binding(
    pdb_file: str,
    output_file: str,
    cation_name: str = "CA",
    binding_residues: List[int] = None
) -> bool:
    """
    Visualize cation binding site.

    Parameters
    ----------
    pdb_file : str
        Input PDB file (should contain cation)
    output_file : str
        Output image file
    cation_name : str
        Name of cation (CA, MG, ZN, etc.)
    binding_residues : list, optional
        Residues coordinating the cation

    Returns
    -------
    bool
        True if successful
    """
    commands = [
        "# Basic setup",
        "hide everything",
        "show cartoon, model",
        "color gray80, model",
        "set cartoon_transparency, 0.7",
        "",
        f"# Show cation as sphere",
        f"select cation, resn {cation_name}",
        "show spheres, cation",
        f"color {'green' if cation_name == 'CA' else 'cyan' if cation_name == 'MG' else 'gray50'}, cation",
        "set sphere_scale, 0.5, cation",
    ]

    if binding_residues:
        res_sel = "+".join(str(r) for r in binding_residues)
        commands.extend([
            "",
            f"# Show binding residues",
            f"select binding, resi {res_sel}",
            "show sticks, binding",
            "color yellow, binding",
            "",
            "# Show distances to cation",
            "distance coordination, cation, binding and (name OD* or name OE* or name ND* or name NE* or name SG), 3.5",
            "hide labels, coordination",
            "color black, coordination",
        ])

    commands.extend([
        "",
        "# Center on binding site",
        "center cation",
        "zoom cation, 10",
    ])

    script = generate_pymol_script(pdb_file, output_file, commands)
    return run_pymol_script(script)


def compare_structures(
    pdb_file1: str,
    pdb_file2: str,
    output_file: str,
    align: bool = True
) -> bool:
    """
    Compare two structures side by side or superimposed.

    Parameters
    ----------
    pdb_file1 : str
        First PDB file
    pdb_file2 : str
        Second PDB file
    output_file : str
        Output image file
    align : bool
        Whether to align structures

    Returns
    -------
    bool
        True if successful
    """
    commands = [
        f"load {pdb_file1}, model1",
        f"load {pdb_file2}, model2",
        "",
        "# Color differently",
        "color cyan, model1",
        "color orange, model2",
        "",
        "# Show as cartoon",
        "hide everything",
        "show cartoon",
    ]

    if align:
        commands.extend([
            "",
            "# Align structures",
            "align model1, model2",
        ])

    commands.extend([
        "",
        "# Orient view",
        "orient",
        "zoom",
    ])

    # Need custom script since we're loading two files
    script = f"""# PyMOL comparison script
bg_color white
set ray_opaque_background, on
set antialias, 2

{chr(10).join(commands)}

viewport 1200, 900
ray
png {output_file}, dpi=300
quit
"""
    return run_pymol_script(script)


class StructureVisualizer:
    """
    Unified structure visualization class.

    Parameters
    ----------
    pdb_file : str
        Path to PDB file
    output_dir : str
        Output directory for images

    Example
    -------
    >>> viz = StructureVisualizer("model.pdb", "figures")
    >>> viz.active_site([123, 156, 189], "p3e_fig1.png")
    >>> viz.secondary_structure("p3g_fig1.png")
    """

    def __init__(self, pdb_file: str, output_dir: str = "."):
        self.pdb_file = Path(pdb_file)
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)

    def active_site(
        self,
        residues: List[int],
        output_name: str,
        conserved: List[int] = None,
        non_conserved: List[int] = None
    ) -> bool:
        """Generate active site figure."""
        output_path = self.output_dir / output_name
        return visualize_active_site(
            str(self.pdb_file),
            residues,
            str(output_path),
            conserved,
            non_conserved
        )

    def problematic_regions(
        self,
        regions: List[Tuple[int, int]],
        output_name: str
    ) -> bool:
        """Generate problematic regions figure."""
        output_path = self.output_dir / output_name
        return visualize_problematic_regions(
            str(self.pdb_file),
            regions,
            str(output_path)
        )

    def secondary_structure(self, output_name: str, highlight: Dict = None) -> bool:
        """Generate secondary structure figure."""
        output_path = self.output_dir / output_name
        return visualize_secondary_structure(
            str(self.pdb_file),
            str(output_path),
            highlight
        )

    def cation_site(
        self,
        output_name: str,
        cation: str = "CA",
        binding_residues: List[int] = None
    ) -> bool:
        """Generate cation binding site figure."""
        output_path = self.output_dir / output_name
        return visualize_cation_binding(
            str(self.pdb_file),
            str(output_path),
            cation,
            binding_residues
        )
