>P1;1u84
structureX:1u84:1:A:END:A::::
GQQLNRLLLEWIGAWDPFGLGKDAYDVEAASVLQAVYETEDARTLAARIQSIYEFAFDEPIPFPHCLKLARRLLELKQAAS*

>P1;HD100
sequence:HD100::::::::
GQQLNRLLLEWIGAWDPFGLGKDAYDVEAEAVLQAVYETESAFDLAMRIMWIYVFAFNRPIPFSHAQKLARRLLELKQAASSPLP*
