"""
MODELLER script generators and runner utilities.

This module provides functions to generate MODELLER scripts for:
- Single template modeling
- Multiple template modeling
- Loop refinement
- Model evaluation

Example Usage
-------------
>>> from src.modeller import generate_multi_template_script, ModellerRunner
>>> # Generate script for multi-template modeling
>>> script = generate_multi_template_script(
...     alignment_file="Modeller_Templates/combined_alignment.pir",
...     target_id="MyProtein",
...     template_ids=["1abc", "2def"],
...     num_models=5
... )
>>> # Run MODELLER
>>> runner = ModellerRunner()
>>> runner.run_script(script, output_dir="Models")
"""

from pathlib import Path
from typing import List, Optional, Tuple
import subprocess
import os


def generate_single_template_script(
    alignment_file: str,
    target_id: str,
    template_id: str,
    num_models: int = 5,
    output_prefix: str = "model"
) -> str:
    """
    Generate a MODELLER script for single template modeling.

    Parameters
    ----------
    alignment_file : str
        Path to PIR alignment file
    target_id : str
        Target sequence ID in alignment
    template_id : str
        Template structure ID in alignment
    num_models : int
        Number of models to generate (default 5)
    output_prefix : str
        Prefix for output model files

    Returns
    -------
    str
        MODELLER Python script content
    """
    script = f'''# MODELLER script for single template homology modeling
# Generated by AlphaBald Pipeline

from modeller import *
from modeller.automodel import *

# Set up environment
env = Environ()
env.io.atom_files_directory = ['.', '../Templates', '../Modeller_Templates']

# Create alignment object
aln = Alignment(env)

# Build model using automodel class
class MyModel(AutoModel):
    def special_patches(self, aln):
        # Override to add special patches if needed
        pass

a = MyModel(
    env,
    alnfile='{alignment_file}',
    knowns='{template_id}',
    sequence='{target_id}',
    assess_methods=(assess.DOPE, assess.GA341)
)

# Set model parameters
a.starting_model = 1
a.ending_model = {num_models}

# Generate models
a.make()

# Print summary of results
print("\\n" + "="*60)
print("MODEL ASSESSMENT SUMMARY")
print("="*60)
for model in a.outputs:
    print(f"Model: {{model['name']}}")
    print(f"  DOPE score: {{model['DOPE score']:.2f}}")
    print(f"  GA341 score: {{model['GA341 score'][0]:.4f}}")
    print("-"*40)
'''
    return script


def generate_multi_template_script(
    alignment_file: str,
    target_id: str,
    template_ids: List[str],
    num_models: int = 5,
    output_prefix: str = "model"
) -> str:
    """
    Generate a MODELLER script for multiple template modeling.

    Parameters
    ----------
    alignment_file : str
        Path to PIR alignment file
    target_id : str
        Target sequence ID in alignment
    template_ids : list
        List of template structure IDs in alignment
    num_models : int
        Number of models to generate (default 5)
    output_prefix : str
        Prefix for output model files

    Returns
    -------
    str
        MODELLER Python script content
    """
    template_tuple = str(tuple(template_ids)) if len(template_ids) > 1 else f"('{template_ids[0]}',)"

    script = f'''# MODELLER script for multiple template homology modeling
# Generated by AlphaBald Pipeline

from modeller import *
from modeller.automodel import *

# Set up environment
env = Environ()
env.io.atom_files_directory = ['.', '../Templates', '../Modeller_Templates']

# Set verbose output
log.verbose()

# Create alignment object and build model
a = AutoModel(
    env,
    alnfile='{alignment_file}',
    knowns={template_tuple},
    sequence='{target_id}',
    assess_methods=(assess.DOPE, assess.GA341)
)

# Set model parameters
a.starting_model = 1
a.ending_model = {num_models}

# Optimization parameters (can be adjusted for better results)
a.library_schedule = autosched.slow
a.max_var_iterations = 300
a.md_level = refine.slow

# Generate models
a.make()

# Select best model based on DOPE score
best_model = min(a.outputs, key=lambda x: x['DOPE score'])

# Print summary of results
print("\\n" + "="*60)
print("MODEL ASSESSMENT SUMMARY")
print("="*60)
for model in a.outputs:
    marker = " <-- BEST" if model == best_model else ""
    print(f"Model: {{model['name']}}{{marker}}")
    print(f"  DOPE score: {{model['DOPE score']:.2f}}")
    print(f"  GA341 score: {{model['GA341 score'][0]:.4f}}")
    print("-"*40)

print(f"\\nBest model: {{best_model['name']}}")
print(f"Best DOPE score: {{best_model['DOPE score']:.2f}}")
'''
    return script


def generate_loop_refinement_script(
    pdb_file: str,
    target_id: str,
    loop_residues: List[Tuple[int, int]],
    num_models: int = 5
) -> str:
    """
    Generate a MODELLER script for loop refinement.

    Parameters
    ----------
    pdb_file : str
        Path to PDB file to refine
    target_id : str
        Target sequence ID
    loop_residues : list
        List of (start, end) tuples for loop regions to refine
    num_models : int
        Number of refined models to generate

    Returns
    -------
    str
        MODELLER Python script content
    """
    loop_selection = " or ".join([
        f"(self.residue_range('{start}:', '{end}:'))"
        for start, end in loop_residues
    ])

    script = f'''# MODELLER script for loop refinement
# Generated by AlphaBald Pipeline

from modeller import *
from modeller.automodel import *

# Set up environment
env = Environ()
env.io.atom_files_directory = ['.', '../Templates', '../Modeller_Templates']

# Define loop model class
class LoopModel(LoopModel):
    def select_loop_atoms(self):
        return Selection({loop_selection})

# Create and configure loop model
a = LoopModel(
    env,
    inimodel='{pdb_file}',
    sequence='{target_id}',
    loop_assess_methods=assess.DOPE
)

# Set parameters
a.loop.starting_model = 1
a.loop.ending_model = {num_models}
a.loop.md_level = refine.slow

# Generate refined models
a.make()

# Print summary
print("\\n" + "="*60)
print("LOOP REFINEMENT SUMMARY")
print("="*60)
for model in a.loop.outputs:
    print(f"Model: {{model['name']}}")
    print(f"  DOPE score: {{model['DOPE score']:.2f}}")
    print("-"*40)
'''
    return script


def generate_evaluation_script(
    pdb_file: str,
    output_profile: str = "dope_profile.txt"
) -> str:
    """
    Generate a MODELLER script for model evaluation.

    Parameters
    ----------
    pdb_file : str
        Path to PDB file to evaluate
    output_profile : str
        Output file for DOPE profile

    Returns
    -------
    str
        MODELLER Python script content
    """
    script = f'''# MODELLER script for model evaluation
# Generated by AlphaBald Pipeline

from modeller import *
from modeller.scripts import complete_pdb

# Set up environment
env = Environ()
env.libs.topology.read(file='$(LIB)/top_heav.lib')
env.libs.parameters.read(file='$(LIB)/par.lib')

# Read and complete PDB (add missing atoms)
mdl = complete_pdb(env, '{pdb_file}')

# Select all atoms for DOPE calculation
s = Selection(mdl)

# Calculate DOPE score profile
s.assess_dope(
    output='ENERGY_PROFILE NO_REPORT',
    file='{output_profile}',
    normalize_profile=True,
    smoothing_window=15
)

# Calculate overall scores
print("\\n" + "="*60)
print("MODEL EVALUATION")
print("="*60)
print(f"PDB file: {pdb_file}")

# DOPE score
score = s.assess_dope()
print(f"DOPE score: {{score:.2f}}")

# Per-residue DOPE profile saved to file
print(f"DOPE profile saved to: {output_profile}")
'''
    return script


def generate_alignment_checking_script(alignment_file: str) -> str:
    """
    Generate a MODELLER script to check alignment quality.

    Parameters
    ----------
    alignment_file : str
        Path to PIR alignment file

    Returns
    -------
    str
        MODELLER Python script content
    """
    script = f'''# MODELLER script for alignment quality checking
# Generated by AlphaBald Pipeline

from modeller import *

# Set up environment
env = Environ()
env.io.atom_files_directory = ['.', '../Templates', '../Modeller_Templates']

# Read alignment
aln = Alignment(env)
aln.append(file='{alignment_file}', align_codes='all')

# Check alignment quality
aln.check()

# Write alignment in other formats for visualization
aln.write(file='alignment_check.ali', alignment_format='PIR')
aln.write(file='alignment_check.pap', alignment_format='PAP')

print("\\nAlignment check completed.")
print("See alignment_check.pap for formatted alignment.")
'''
    return script


class ModellerRunner:
    """
    Utility class to run MODELLER scripts.

    Example
    -------
    >>> runner = ModellerRunner()
    >>> runner.run_script(script_content, output_dir="Models")
    """

    def __init__(self, modeller_path: Optional[str] = None):
        """
        Initialize the MODELLER runner.

        Parameters
        ----------
        modeller_path : str, optional
            Path to MODELLER executable. If None, assumes 'mod*' is in PATH
            or that modeller is importable via Python.
        """
        self.modeller_path = modeller_path or self._find_modeller()

    def _find_modeller(self) -> str:
        """Find MODELLER executable in PATH or check if importable."""
        # First check if modeller is importable (conda environment)
        try:
            import modeller
            return 'python'  # Use python directly since modeller is importable
        except ImportError:
            pass

        # Try common MODELLER executable names
        for name in ['mod10.5', 'mod10.4', 'mod10.3', 'mod10.2', 'mod10.1', 'mod10.0', 'modpy.sh']:
            try:
                result = subprocess.run(['which', name], capture_output=True, text=True)
                if result.returncode == 0:
                    return name
            except Exception:
                pass
        return 'python'  # Fall back to Python

    def run_script(
        self,
        script_content: str,
        output_dir: str = ".",
        script_name: str = "modeller_script.py"
    ) -> bool:
        """
        Run a MODELLER script.

        Parameters
        ----------
        script_content : str
            Python script content for MODELLER
        output_dir : str
            Directory to run the script in
        script_name : str
            Name for the script file

        Returns
        -------
        bool
            True if successful, False otherwise
        """
        output_path = Path(output_dir)
        output_path.mkdir(exist_ok=True)

        script_file = output_path / script_name
        with open(script_file, 'w') as f:
            f.write(script_content)

        print(f"Running MODELLER script: {script_file}")

        try:
            # Change to output directory and run
            original_dir = os.getcwd()
            os.chdir(output_path)

            if self.modeller_path == 'python':
                result = subprocess.run(
                    ['python', script_name],
                    capture_output=True,
                    text=True
                )
            else:
                result = subprocess.run(
                    [self.modeller_path, script_name],
                    capture_output=True,
                    text=True
                )

            os.chdir(original_dir)

            if result.returncode == 0:
                print("MODELLER completed successfully!")
                print(result.stdout)
                return True
            else:
                print(f"MODELLER failed with error:\n{result.stderr}")
                return False

        except Exception as e:
            print(f"Error running MODELLER: {e}")
            return False

    def save_script(
        self,
        script_content: str,
        output_path: str
    ) -> Path:
        """
        Save a MODELLER script without running it.

        Parameters
        ----------
        script_content : str
            Python script content for MODELLER
        output_path : str
            Path to save the script

        Returns
        -------
        Path
            Path to saved script
        """
        path = Path(output_path)
        path.parent.mkdir(exist_ok=True, parents=True)

        with open(path, 'w') as f:
            f.write(script_content)

        print(f"Script saved to: {path}")
        return path


def create_modeller_scripts_for_pipeline(
    alignment_file: str = "Modeller_Templates/combined_alignment.pir",
    target_id: str = "target",
    template_ids: Optional[List[str]] = None,
    output_dir: str = "Modeller_Templates",
    num_models: int = 5
) -> dict:
    """
    Create all MODELLER scripts needed for the pipeline.

    Parameters
    ----------
    alignment_file : str
        Path to PIR alignment file
    target_id : str
        Target sequence ID
    template_ids : list, optional
        List of template IDs. If None, will be parsed from alignment file.
    output_dir : str
        Output directory for scripts
    num_models : int
        Number of models to generate

    Returns
    -------
    dict
        Dictionary with script paths
    """
    output_path = Path(output_dir)
    output_path.mkdir(exist_ok=True)

    # Parse template IDs from alignment if not provided
    if template_ids is None:
        template_ids = _parse_templates_from_pir(alignment_file)

    scripts = {}

    # Generate main modeling script
    if len(template_ids) == 1:
        main_script = generate_single_template_script(
            alignment_file, target_id, template_ids[0], num_models
        )
    else:
        main_script = generate_multi_template_script(
            alignment_file, target_id, template_ids, num_models
        )

    main_path = output_path / "build_model.py"
    with open(main_path, 'w') as f:
        f.write(main_script)
    scripts['build_model'] = main_path

    # Generate evaluation script
    eval_script = generate_evaluation_script("${TARGET_ID}.B99990001.pdb")
    eval_path = output_path / "evaluate_model.py"
    with open(eval_path, 'w') as f:
        f.write(eval_script)
    scripts['evaluate_model'] = eval_path

    # Generate alignment check script
    check_script = generate_alignment_checking_script(alignment_file)
    check_path = output_path / "check_alignment.py"
    with open(check_path, 'w') as f:
        f.write(check_script)
    scripts['check_alignment'] = check_path

    print(f"MODELLER scripts created in {output_dir}:")
    for name, path in scripts.items():
        print(f"  - {name}: {path.name}")

    return scripts


def _parse_templates_from_pir(pir_file: str) -> List[str]:
    """Parse template IDs from a PIR alignment file."""
    templates = []
    with open(pir_file) as f:
        for line in f:
            if line.startswith('>P1;'):
                seq_id = line.strip().split(';')[1]
                # Check if this is a structure (next line starts with 'structureX')
            elif line.startswith('structureX:'):
                templates.append(seq_id)
            elif line.startswith('sequence:'):
                # This is the target, not a template
                pass
    return templates
